### PR TITLE
Add support for ScanTime

### PR DESCRIPTION
**Pull request by TheNitek**
In my setup it takes up to 4ms after the output is set to low, for the input to also reach low, so I added a scanTime option to account for that.

### CODE REVIEW

**Comment by Nullkraft** [comment]
Hi TheNitek, I have to admit that I was initially confused because I didn't understand how adding a delay() would reduce a 4 millisecond delay.  But I think I see now that you probably weren't getting proper scans because the pin on line 93 that was supposed to be set low took as much as 4 milliseconds before it would change.

If I'm correct would you mind describing your setup for me.  Knowing what hardware is being affected by any piece of code lets me add a comment that explains why it is there.  That will prevent future me, or anyone who may fork the code, from removing it.

Also, please let me know if I'm wrong.  Right now I'm tempted to remove the scanTime delay and replace it with a while-loop that tests for the selected pin to go low.

**Comment by TheNitek** [comment]
Fun project: I am turning [this toy](https://www.tiktok.com/@thenitek/video/7069862598530993413) into a keyboard using a ESP32-S2. Internal wiring (roughly) matches a keypad, but of course the wires cat pretty long for the buttons at the end (> 50cm one-way). This introduces some latency between setting the output pin and input pin going low.
My tests show that in this case it takes about 4ms to reliably detect the signal.

A while loop won't do much good because buttons near the ESP react much faster (<1ms) then the ones on the other end, but might me in the same "column". So even if polling within a while loop I'd still need to do this for the full 4ms, because I might miss a button press on the very end of the piano otherwise.

I agree that his is probably not the most elegant solution, but it's simple and works 😄

**Comment by Nullkraft** [comment]
>> I agree that his is probably not the most elegant solution, but it's simple and works 😄

The while loop may introduce far more complexity than I first considered so I have to agree that simple is better.  But what I would also like to avoid is the unexpected delay that you get by calling delay(0).  So maybe an if block to check for scanTime==0 and just bail before calling delay()?  The performance difference, if any, would need to be measured before deciding.

Maybe?:
        pin_mode(columnPins[c],OUTPUT);
        pin_write(columnPins[c], LOW);    // Begin column pulse output.
        if (scanTime>0) {
            delay(scanTime);
        }
        for (byte r=0; r<sizeKpd.rows; r++) {
            bitWrite(bitMap[r], c, !pin_read(rowPins[r]));  // keypress is active low so invert to high.
        }

It's probably important at this time to point out that I have three things that I try to optimize for;  1) Speed. It's okay to use more program space and memory to go faster.  2) Reduced program and memory space.  As a library I should consume as few resources as possible.  3) Make the source code as simple to read/understand as possible.  That should allow less experienced library authors to extend the keypad library.

Of course the best result is to only use functions from the Arduino reference, use no program space or memory, and have the Arduino run faster than it did before adding my code. 😄

**Comment by TheNitek** [comment]
My code already includes this if since I wanted to avoid affecting any of the already exsting use cases 😃

**Comment by Nullkraft** [comment]
Ahh, great minds and all that, hey? ;)

So I'm not sure how this works but I would like your latest changes plus a comment appended to the delay(scanTime) line.  I recommend that it look something like this;

    delay(scanTime);   // DO NOT REMOVE! Prevents problems with the <Name & Model of keyboard>; https://github.com/Nullkraft/Keypad/pull/15

That will let other developers know what problem the code is meant to solve.

What I'm not sure about is how you would update the pull-request.  Since I'm asking for the comment to refer to this page do I merge this request first and then have you submit an update?  Any ideas?

**Comment by TheNitek** [comment]
I added the comment, pull request is updated automatically. Somewhat self-referential now 😃

**Comment by Nullkraft** [comment]
That's cool.  I like it.  But I kind of needed you to replace the <Name & Model of keyboard> with the actual name and model of the keyboard so others can check it out.

**Comment by TheNitek** [comment]
done

**Comment by Nullkraft** [comment]
Now we're cooking with gas.  All merged and a big thanks from the entire team over at Nullkraft.  Well, me.

**Pull request merged**
