### PR TITLE
Add support for input/output shift registers

### PR DESCRIPTION
**Pull request by dzervas**
I created 3 new classes:
- KeypadShiftIn
- KeypadShiftOut
- KeypadShiftInOut

The change the way that the matrix is scanned in order to use either an input shift register to scan for a column or output shift register to scan for a row or both.

I've also made some changes such as uniquely naming the definitions of this project to avoid any collisions (such as #1 ) and removed unneccesary `pinMode` commands during the scan loop and moved them to begin.

### CODE REVIEW

**Comment by Nullkraft** [comment]
Hello dzervas,

  I have to apologize for not posting any kind of a design document.  I need to explain because a couple of the changes you made, although they simplify the code and improve efficiency, are contrary to a couple of requirements I made for myself.  There's no way you could have known.

Design requirements:
Multiplexed pins:  I wanted to be able to multiplex the data pins with the LCD Library.  I even talked Limor Fried, Adafruit, into modifying the LCD library so that it would do the same thing.  With the pinmodes being called on each cycle it will "reclaim" the pins after another library "borrowed" them away.

Virtual pin functions:  Another library writer wanted to add I2C to the keypads and so I virtualized the pin reads/writes so that he could simply extend the Keypad library.  I'll have to look at your shift functions to see if they duplicate his efforts.  Sorry I haven't had time today.  I just finished rebuilding my workstation after a nasty little surprise.

Definition names:  The names I chose, I can't even remember how many years ago, were chosen to help other library authors better understand the intent of the code.  In hindsight my choices were probably a little too generic. My only concern is with NO_KEY.  I exposed that in my earliest example sketches and I don't know if anybody is depending on that remaining the same.  All the other names are just used internally so should be more flexible.  I had a couple of other people who had a problem with this so I added namespaces to the code and sent them a private copy.  Not my best decision.

There's probably more but I'm about to head out the door and won't be back till later tonight. I will start reviewing your code changes then. And lastly, this is my first pull request ever so I don't really know the steps for dealing with it.  Any information would be helpful otherwise I need to spend a little time learning not to screw it up.

**Review by Nullkraft — APPROVED** [review]
Dimitris, if you would like to contact me my email is in the source files. Mine is the technologist.com email.

**Comment by dzervas** [comment]
OOOOOOH! NOW it makes sense! The code is super clean & neat and I saw some "bad practices" and it left me wandering!

Sorry that I was off for so long! I had to make my keyboard work (4 days to debug a broken trace that was 1.5MOhm instead of 0.1Ohm...).

At this point I'm not sure that it's a good idea to merge. I've changed stuff and most probably broken stuff. Your points for backward compatibility are very true and we should deffo keep at least SOME of the commonly used definitions pointing to the new ones and throw a deprecation warning forever, if you're on par with my train of thought on the naming - NOW it's the time to speak :stuck_out_tongue:, if we make a change lets make it count.

I've pivoted rows & columns as my use case is a regular keyboard (BTW https://www.thingiverse.com/thing:3478494 is amazing to say the least) which has <10 rows but many columns.

I also can't test the `ShiftOut`, as I don't have such a shift register at hand (can find one though, if you're actually into maintaining this library). Code there might need a bit polishing/corrections.

I'm not sure but maybe platformio's test suite can help us?

Last but not least, the project that I use this lib is here (has gerbers as well):  https://github.com/dzervas/plikter

**Comment by Nullkraft** [comment]
Too late, I just did the merge.  I guess I get to learn how to roll things back now. :)

 

Just to let you know all the bad practices are mine.  Alexander did the all the code for generating events. I did all the code for the state machine. I generally work with hardware and my main programming language is solder. Alexander moved to working upstream at http://wiring.org.co/

 

And I understand about being off for so long. I'm right in the middle of three projects laying out circuit boards and assembling prototypes. When I'm done with that then I will start writing code to make them work.

 

As for the keypad I just sent you a github invitation so it should be easier to get things done. Also, there's another person who asked me to submit the latest change to platform.io

It seems they are running slightly older code but I can't figure out how to submit an update. It was originally uploaded by someone else.

 

I don't know how many columns you needed but you could have increased the number of columns by changing the variables to unsigned long or unsigned int. That would have provided 32 columns instead of only 16.

 

Sent: Friday, May 15, 2020 at 4:29 PM

**Pull request merged**
