### PR TITLE
Add Object Method Callback + fix bug

### PR DESCRIPTION
**Pull request by estherDow**
I added a callback template, that takes an Object and a static function, that calls a member in before mentioned object.
I use this to keep state of menu positions, etc. inside a separate object.

Also initialized all function pointers to 0, because depending upon implementation, an uninitialized pointer to a function might not be null. In my case this led to crashes I was not able to pin down for basically all this weekend :D

### CODE REVIEW

**Comment by Nullkraft** [comment]
Thanks Kenneth.  I plan on merging your changes but I have a couple of questions.  I wanted to let you know that Alexander was the one who wrote the event listener code.  It took me quite some time to understand it on my own.  So I'm curious how you are using the changes you made?  I tried to look through your git but I couldn't find where you are using it.

The other question I have is to ask if you could provide a simple example of how to use the new event listener?

**Comment by estherDow** [comment]
Hi NullKraft,
I intend to expose a static method that can call member functions by using
`reinterpret_cast<ClassName *>(PointerToObject)->memberFunction(char Key)`
This way I can change the state of menus or other things without having to rely on global variables.
I pushed an example, more out of reflex. It needs testing, I will hope to do tonight or tomorrow.
All my best

**Comment by Nullkraft** [comment]
Cool.  I think I see what is happening.  Looks good to me.  But now you got me thinking...
Before I head down the rabbit hole trying to find a solution, do you think it would be possible to use polymorphism or C++ templates, or whatever, to combine all the event listeners under one function name?

Also, let me know once you've tested the example and I'll merge the changes.

**Comment by estherDow** [comment]
Possibly writing an observer could be in place. This way `Keypad` holds a list of pointers to registered objects inheriting from a common Interface each needing to implement a method called `update` or the like.  On Key Event `Keypad `iterates through that list and calls each update method.

**Comment by Nullkraft** [comment]
Hey kennethDow, I just merged your changes into the keypad library.  I also wanted to say thank you.

**Comment by estherDow** [comment]
Hey Nullkraft, thanks! Let´s talk about improving this towards an observer pattern.
Thanks for your patience

**Comment by Nullkraft** [comment]
Looking forward to it.  As I said, I last learned C++ in 1999 so my knowledge is 2 decades out of date.  So I ran over to Wikipedia and I have to admit that it looks like the Keypad library shouldn't be too hard to make it work using the observer pattern. 

How do you feel about being added as a collaborator?  I think it would make things a lot easier.

**Comment by estherDow** [comment]
I'd be humbled to be added as a collaborator. thanks!

**Comment by Nullkraft** [comment]
Okay, I added you as a collaborator to the Keypad library but the status says you have to accept it.  I don't know if you got a message or not so I'm sending it from here just to be sure.
 

Sent: Tuesday, March 22, 2022 at 4:48 AM

**Pull request merged**
